FROM golang:1.26-bookworm AS builder

WORKDIR /build
COPY . .
RUN go mod tidy && \
    CGO_ENABLED=0 GOOS=linux go build -o netclient -ldflags="-s -w" .

FROM scratch
COPY --from=builder /build/netclient /netclient
