package config

import (
	"bytes"
	"errors"
	"os"
	"os/exec"
	"strings"

	"github.com/gravitl/netmaker/logger"
)

type resolvconfFlavor int

const (
	systemdStub resolvconfFlavor = iota
	systemdUplink
	resolvconf
	openresolv
	file
	unknown
)

func NewManager(opts ...ManagerOption) (Manager, error) {
	flavor, err := getResolvconfFlavor()
	if err != nil {
		return nil, err
	}

	switch flavor {
	case systemdStub:
		logger.Log(0, "creating systemd stub manager")
		return newSystemdStubManager(opts...)
	case systemdUplink:
		logger.Log(0, "creating systemd uplink manager")
		return newSystemdUplinkManager(opts...)
	case resolvconf:
		logger.Log(0, "creating resolvconf manager")
		return newResolvconfManager(opts...)
	case openresolv:
		logger.Log(0, "creating openresolv manager")
		return newOpenresolvManager(opts...)
	default:
		logger.Log(0, "creating file manager")
		return newFileManager(opts...)
	}
}

func getResolvconfFlavor() (resolvconfFlavor, error) {
	stat, err := os.Lstat("/etc/resolv.conf")
	if err != nil {
		return unknown, err
	}

	if stat.Mode()&os.ModeSymlink == os.ModeSymlink {
		target, err := os.Readlink("/etc/resolv.conf")
		if err != nil {
			return unknown, err
		}

		if strings.HasSuffix(target, "/run/systemd/resolve/stub-resolv.conf") {
			return systemdStub, nil
		} else if strings.HasSuffix(target, "/run/systemd/resolve/resolv.conf") {
			return systemdUplink, nil
		}
	}

	// Fallback: /etc/resolv.conf is not a symlink (e.g. bind-mounted into a container from a
	// systemd-resolved host — Docker resolves the symlink and mounts the target file directly).
	//
	// Two signals must agree before we classify as systemd-managed:
	//   1. systemd-resolved is active on this host (systemctl is-active exits 0)
	//   2. /etc/resolv.conf itself carries a systemd-resolved fingerprint
	//
	// (1) alone is a false positive in containers that run their own systemd init
	// (e.g. WSL with privileged containers) while the host's resolv.conf is managed
	// by something else entirely (wsl.conf, static file, etc). Without (2) we would
	// hand DNS to the container's systemd-resolved, which has no effect on the host.
	if exec.Command("systemctl", "is-active", "--quiet", "systemd-resolved").Run() == nil &&
		isSystemdManagedResolvConf() {
		if isSystemdStubMode() {
			return systemdStub, nil
		}
		return systemdUplink, nil
	}

	resolvconfPath, err := exec.LookPath("resolvconf")
	if err != nil {
		var execErr *exec.Error
		if errors.As(err, &execErr) && errors.Is(execErr.Err, exec.ErrNotFound) {
			return file, nil
		}

		return unknown, err
	}

	stat, err = os.Lstat(resolvconfPath)
	if err != nil {
		return unknown, err
	}

	if stat.Mode()&os.ModeSymlink == os.ModeSymlink {
		target, err := os.Readlink(resolvconfPath)
		if err != nil {
			return unknown, err
		}

		if strings.HasSuffix(target, "resolvectl") {
			return file, nil
		}
	}

	output, err := exec.Command("resolvconf", "--version").CombinedOutput()
	if err != nil {
		var execErr *exec.ExitError
		if errors.As(err, &execErr) && execErr.ExitCode() == 99 {
			return resolvconf, nil
		}
	}

	if bytes.HasPrefix(output, []byte("Debian resolvconf")) {
		return resolvconf, nil
	}

	return openresolv, nil
}

// isSystemdStubMode returns true if systemd-resolved is running in stub mode
// (nameserver 127.0.0.53), as opposed to uplink mode (real upstream DNS IP).
// Reads /etc/resolv.conf directly — works both on bare hosts (symlink target)
// and inside containers where the file is bind-mounted from the host.
func isSystemdStubMode() bool {
	data, err := os.ReadFile("/etc/resolv.conf")
	if err != nil {
		return false
	}
	return strings.Contains(string(data), "127.0.0.53")
}

// isSystemdManagedResolvConf returns true only if /etc/resolv.conf itself
// carries a fingerprint that systemd-resolved owns it — the 127.0.0.53 stub
// nameserver, or one of the self-identifying comment headers that systemd
// writes at the top of the file.
//
// On WSL and similar environments where the container has its own systemd
// init but the host's resolv.conf is generated by something else (wsl.conf,
// hand-written, docker-entrypoint, etc), this returns false even though
// `systemctl is-active systemd-resolved` may succeed inside the container.
// Gating the systemd-detection fallback on this prevents us from handing
// DNS to the container's systemd-resolved where it has no effect on the host.
func isSystemdManagedResolvConf() bool {
	data, err := os.ReadFile("/etc/resolv.conf")
	if err != nil {
		return false
	}
	content := string(data)
	if strings.Contains(content, "127.0.0.53") {
		return true
	}
	if strings.Contains(content, "Generated by systemd-resolved") ||
		strings.Contains(content, "This file is managed by man:systemd-resolved") {
		return true
	}
	return false
}
